#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${1:-}"
if [[ -z "$REPO_ROOT" ]]; then
  echo "Usage: apply-config.sh <repo-root>" >&2
  exit 1
fi

TARGET_HOME="${TARGET_HOME:-$HOME}"
TARGET_FILE="$TARGET_HOME/.tmux.conf"
BACKUP_DIR="$TARGET_HOME/.tmux-backups"

mkdir -p "$BACKUP_DIR"

BACKUP_STAMP="$(date +%Y%m%d%H%M%S).$$.$RANDOM"
if [[ -f "$TARGET_FILE" ]]; then
  BACKUP_FILE="$BACKUP_DIR/.tmux.conf.${BACKUP_STAMP}.bak"
  cp "$TARGET_FILE" "$BACKUP_FILE"
else
  : > "$BACKUP_DIR/.tmux.conf.${BACKUP_STAMP}.absent"
fi

cat > "$TARGET_FILE" <<EOF
# generated by tmux apply-config.sh
set-environment -g TMUX_REPO_ROOT "$REPO_ROOT"
source-file "$REPO_ROOT/tmux/tmux.conf"
EOF
