"""Template Renderer for Task Flow

Renders templates with variable substitution and conditionals.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Callable

from packaging.version import Version, InvalidVersion


class TemplateRenderer:
    """模板渲染器：替换变量和处理条件逻辑"""

    # 预编译的正则模式
    _PLACEHOLDER_PATTERN = re.compile(r'\{([A-Z_][A-Z0-9_]*)\}')
    _CONDITIONAL_PATTERN = re.compile(r'\{IF:([A-Z_][A-Z0-9_]*)\}(.+?)\{ENDIF\}', re.DOTALL)

    # 模板变量定义（支持静态值和可调用对象）
    VARIABLES: dict[str, str | Callable] = {
        'VERSION': '2.3.0',
        'DATE': lambda: datetime.now().strftime('%Y-%m-%d'),
        'YEAR': lambda: str(datetime.now().year),
        'MONTH': lambda: datetime.now().strftime('%m'),
        'DAY': lambda: datetime.now().strftime('%d'),
    }

    @classmethod
    def set_version(cls, version: str) -> None:
        """设置版本号（用于测试或覆盖）

        Args:
            version: 版本号字符串

        Raises:
            VersionParseError: 版本号格式无效
        """
        try:
            Version(version)  # 验证版本号格式
        except InvalidVersion as e:
            from .exceptions import VersionParseError
            raise VersionParseError(version, str(e))
        cls.VARIABLES['VERSION'] = version

    @classmethod
    def get_version(cls) -> str:
        """获取当前版本号

        Returns:
            版本号字符串
        """
        version = cls.VARIABLES.get('VERSION', '0.0.0')
        return version() if callable(version) else str(version)

    def render(self, template: str, extra_vars: dict[str, Any] | None = None) -> str:
        """渲染模板，替换变量

        Args:
            template: 模板内容
            extra_vars: 额外的变量（可选）

        Returns:
            渲染后的内容
        """
        result = template

        # 渲染条件逻辑（如果有）
        result = self._render_conditionals(result, extra_vars or {})

        # 渲染变量
        result = self._render_placeholders(result, extra_vars or {})

        return result

    def _render_placeholders(
        self,
        template: str,
        extra_vars: dict[str, Any]
    ) -> str:
        """渲染占位符变量

        Args:
            template: 模板内容
            extra_vars: 额外的变量

        Returns:
            渲染后的内容
        """
        def replace_var(match: re.Match) -> str:
            key = match.group(1)

            # 优先使用额外变量
            if key in extra_vars:
                value = extra_vars[key]
            elif key in self.VARIABLES:
                value = self.VARIABLES[key]
            else:
                return match.group(0)  # 保持原样

            return str(value() if callable(value) else value)

        return self._PLACEHOLDER_PATTERN.sub(replace_var, template)

    def _render_conditionals(
        self,
        template: str,
        extra_vars: dict[str, Any]
    ) -> str:
        """渲染条件逻辑

        Args:
            template: 模板内容
            extra_vars: 额外的变量

        Returns:
            渲染后的内容
        """
        def replace_conditional(match: re.Match) -> str:
            key = match.group(1)
            content = match.group(2)

            # 检查条件是否为真
            value = self._get_var_value(key, extra_vars)
            return content if value else ""

        # Only process conditionals if pattern exists in template
        if '{IF:' in template:
            return self._CONDITIONAL_PATTERN.sub(replace_conditional, template)
        return template

    def _get_var_value(
        self,
        key: str,
        extra_vars: dict[str, Any]
    ) -> Any:
        """获取变量值

        Args:
            key: 变量名
            extra_vars: 额外的变量

        Returns:
            变量值
        """
        if key in extra_vars:
            value = extra_vars[key]
        elif key in self.VARIABLES:
            value = self.VARIABLES[key]
        else:
            return None

        return value() if callable(value) else value

    def render_template_file(
        self,
        template_content: str,
        **extra_vars: Any
    ) -> str:
        """渲染模板文件内容的便捷方法

        Args:
            template_content: 模板内容
            **extra_vars: 额外的变量

        Returns:
            渲染后的内容
        """
        return self.render(template_content, extra_vars)

    @staticmethod
    def add_version_markers(content: str, version: str) -> str:
        """为内容添加版本标记

        Args:
            content: 原始内容
            version: 版本号

        Returns:
            添加了版本标记的内容
        """
        version_line = f"<!-- TASK-FLOW-VERSION:{version} -->"
        section_start = "<!-- TASK-FLOW-SECTION -->"
        section_end = "<!-- END-TASK-FLOW-SECTION -->"
        auto_generated = f"<!-- AUTO-GENERATED BY task-flow v{version} - DO NOT EDIT MANUALLY -->"

        return (
            f"{version_line}\n"
            f"{auto_generated}\n"
            f"{section_start}\n\n"
            f"{content}\n\n"
            f"{section_end}\n"
        )


@dataclass
class RenderContext:
    """渲染上下文，用于管理渲染过程中的状态"""

    variables: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)

    def add_error(self, error: str) -> None:
        """添加错误信息"""
        self.errors.append(error)

    def has_errors(self) -> bool:
        """检查是否有错误"""
        return len(self.errors) > 0

    def get_errors(self) -> list[str]:
        """获取所有错误"""
        return self.errors.copy()
